[package]
name = "cens-r/censor-utils"
description = "Utility modules and data structures for Luau!"

version = "0.2.1"
license = "MIT"

authors = ["Censor <https://github.com/Cens-r>"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]